apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hpa
  template: # inside template we will have a pod specification
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
        - name: go-hpa
          image: axell13/go-hpa
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "100m"
